In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import warnings
warnings.filterwarnings('ignore')


In [4]:
import os
os.getcwd()

'/content'

In [5]:
df=pd.read_csv("salary1.csv")

In [6]:
df.head()

Unnamed: 0  age          Workclass  fnlwgt   education  education-num  \
0           0   39          State-gov   77516   Bachelors             13   
1           1   50   Self-emp-not-inc   83311   Bachelors             13   
2           2   38            Private  215646     HS-grad              9   
3           3   53            Private  234721        11th              7   
4           4   28            Private  338409   Bachelors             13   

        marital-status          occupation    relationship    race      sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   capital-gain  capital-loss  hours-per-week  native-country  Income  
0          2174             0              40   United-States       0  
1             0             0              13   United-States       0  
2             0             0              40   United-States       0  
3             0             0              40   United-States       0  
4             0             0              40            Cuba       0

In [7]:
df.shape

(1032, 16)

In [8]:
df.dtypes

Unnamed: 0         int64
age                int64
Workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
Income             int64
dtype: object

In [9]:
df.isnull().sum()

Unnamed: 0        0
age               0
Workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
Income            0
dtype: int64

In [10]:
#remove unwanted columns permanently
df.drop("Unnamed: 0",axis=1,inplace=True)

In [11]:
df.dtypes

age                int64
Workclass         object
fnlwgt             int64
education         object
education-num      int64
marital-status    object
occupation        object
relationship      object
race              object
sex               object
capital-gain       int64
capital-loss       int64
hours-per-week     int64
native-country    object
Income             int64
dtype: object

In [12]:
#check duplicate
df.duplicated().sum()

0

In [13]:
#separate object type data and numeric type
#data in new dataframe df_obj and hold numeric type
#use select_dtypes() inbuilt method
df_obj=df.select_dtypes('object')
df_num=df.select_dtypes('int64')

In [14]:
df_obj.dtypes

Workclass         object
education         object
marital-status    object
occupation        object
relationship      object
race              object
sex               object
native-country    object
dtype: object

In [15]:
df_num.dtypes

age               int64
fnlwgt            int64
education-num     int64
capital-gain      int64
capital-loss      int64
hours-per-week    int64
Income            int64
dtype: object

In [16]:
df['Workclass'].unique()

array([' State-gov', ' Self-emp-not-inc', ' Private', ' Federal-gov',
       ' Local-gov', ' Self-emp-inc'], dtype=object)

In [17]:
df['marital-status'].unique()

array([' Never-married', ' Married-civ-spouse', ' Divorced',
       ' Married-spouse-absent', ' Separated', ' Married-AF-spouse',
       ' Widowed'], dtype=object)

In [18]:
column=df_obj.columns

In [19]:
column

Index(['Workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country'],
      dtype='object')

In [20]:
from sklearn.preprocessing import LabelEncoder
for col in column :
    #create object of label encoder class
    le=LabelEncoder()
    df_obj[col]=le.fit_transform(df_obj[col])

In [21]:
df_obj.dtypes

Workclass         int64
education         int64
marital-status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
native-country    int64
dtype: object

In [22]:
#merge df_num and df_obj and hold new dataframe df_new
df_new=pd.concat([df_obj,df_num],axis =1)
df_new.dtypes

Workclass         int64
education         int64
marital-status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
native-country    int64
age               int64
fnlwgt            int64
education-num     int64
capital-gain      int64
capital-loss      int64
hours-per-week    int64
Income            int64
dtype: object

In [23]:
df_new.drop("education-num",axis=1,inplace=True)

In [24]:
df_new['Income'].value_counts()

0    778
1    254
Name: Income, dtype: int64

In [25]:
#separate input and output
X=df_new.drop("Income",axis=1) #select input
Y=df_new['Income'] #select output

In [26]:
X.columns

Index(['Workclass', 'education', 'marital-status', 'occupation',
       'relationship', 'race', 'sex', 'native-country', 'age', 'fnlwgt',
       'capital-gain', 'capital-loss', 'hours-per-week'],
      dtype='object')

In [27]:
#train test split 70% and 30%
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,
                                              random_state=1)

In [28]:
X_train.shape,Y_train.shape

((722, 13), (722,))

In [29]:
X_test.shape,Y_test.shape

((310, 13), (310,))

In [30]:
#apply StandardScaler
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.transform(X_test)

In [31]:
X_train

array([[-0.24904966, -0.93217405, -0.37685422, ..., -0.24796148,
        -0.2300775 , -0.10196177],
       [-0.24904966,  0.17523798,  0.95691415, ...,  1.38249871,
        -0.2300775 ,  0.77130512],
       [-0.24904966, -0.37846803,  0.95691415, ..., -0.24796148,
        -0.2300775 , -1.84849555],
       ...,
       [-1.2824626 , -0.65532104, -1.71062259, ..., -0.24796148,
        -0.2300775 ,  1.29526525],
       [ 1.81777623,  0.17523798,  0.95691415, ..., -0.24796148,
        -0.2300775 ,  0.07269161],
       [ 1.81777623,  0.17523798, -0.37685422, ..., -0.24796148,
        -0.2300775 , -0.10196177]])

In [32]:
Y_train

286    1
600    0
691    0
474    0
639    0
      ..
960    0
847    0
715    0
905    0
235    1
Name: Income, Length: 722, dtype: int64

In [33]:
Y_train.value_counts()

0    540
1    182
Name: Income, dtype: int64

In [34]:
#Data is unbalanced
#use RandomOverSampler class: converts minority class into majority class
#first time install imblearn
#!pip install imblearn

In [35]:
from imblearn.over_sampling import RandomOverSampler

In [36]:
#create object of RandomOverSampler class
ros=RandomOverSampler(random_state=1)

In [37]:
#apply ROS on training input and output
X_train1,Y_train1=ros.fit_resample(X_train,Y_train)

In [38]:
Y_train1.value_counts()

1    540
0    540
Name: Income, dtype: int64

In [39]:
Y_test.value_counts()

0    238
1     72
Name: Income, dtype: int64

In [40]:
#apply ROS on training input and output
X_test1,Y_test1=ros.fit_resample(X_test,Y_test)

In [41]:
Y_test1.value_counts()

0    238
1    238
Name: Income, dtype: int64

In [42]:
def create_model(model) :  #here create_model() user defined function name
    #model is a user defined parameter which hold the object of algorithm
    model.fit(X_train1,Y_train1) #train the model with 70% training data
    Y_pred=model.predict(X_test1) #test the model with 30% input
    #print confusion matrix
    print(confusion_matrix(Y_test1,Y_pred))
    #print classification report
    print(classification_report(Y_test1,Y_pred))
    return model

In [43]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [44]:
#Use LogisticRegression Algorithm
from sklearn.linear_model import LogisticRegression

In [45]:
lr=LogisticRegression ()

In [46]:
lr=create_model(lr)

[[172  66]
 [ 83 155]]
              precision    recall  f1-score   support

           0       0.67      0.72      0.70       238
           1       0.70      0.65      0.68       238

    accuracy                           0.69       476
   macro avg       0.69      0.69      0.69       476
weighted avg       0.69      0.69      0.69       476



In [47]:
#recall=65% which is not good amd f1 score is 68% which is not good
#use DecisionTreeClassifier class

In [48]:
from sklearn.tree import DecisionTreeClassifier

In [49]:
#create object
dt=DecisionTreeClassifier(random_state=1)

In [50]:
#call function
dt=create_model(dt)

[[208  30]
 [131 107]]
              precision    recall  f1-score   support

           0       0.61      0.87      0.72       238
           1       0.78      0.45      0.57       238

    accuracy                           0.66       476
   macro avg       0.70      0.66      0.65       476
weighted avg       0.70      0.66      0.65       476



In [51]:
#recall score is 45% which is not good and difference is more than 20

In [52]:
'''for i in range(1,9):
    dt1=DecisionTreeClassifier(random_state=1,max_depth=i)

    print("Max depth: ",i)
    print("Confusion matrix and classification report")
    dt1=create_model(dt1)'''

'for i in range(1,9):\n    dt1=DecisionTreeClassifier(random_state=1,max_depth=i)\n\n    print("Max depth: ",i)\n    print("Confusion matrix and classification report")\n    dt1=create_model(dt1)'

In [53]:
dt1=DecisionTreeClassifier(random_state=1,max_depth=6)
print("Confusion matrix and classification report")
dt1=create_model(dt1)

Confusion matrix and classification report
[[179  59]
 [ 37 201]]
              precision    recall  f1-score   support

           0       0.83      0.75      0.79       238
           1       0.77      0.84      0.81       238

    accuracy                           0.80       476
   macro avg       0.80      0.80      0.80       476
weighted avg       0.80      0.80      0.80       476



In [54]:
#Pruning technique(Gini index) at depth 6= f1 score = 81% and accuracy = 80%

In [55]:
#using entropy
'''for i in range(1,9):
    dt1=DecisionTreeClassifier(random_state=1,max_depth=i,criterion='entropy')

    print("Max depth: ",i)
    print("Confusion matrix and classification report")
    dt1=create_model(dt1)'''

'for i in range(1,9):\n    dt1=DecisionTreeClassifier(random_state=1,max_depth=i,criterion=\'entropy\')\n\n    print("Max depth: ",i)\n    print("Confusion matrix and classification report")\n    dt1=create_model(dt1)'

In [56]:
dt1=DecisionTreeClassifier(random_state=1,max_depth=6,criterion='entropy')
print("Confusion matrix and classification report")
dt1=create_model(dt1)

Confusion matrix and classification report
[[172  66]
 [ 29 209]]
              precision    recall  f1-score   support

           0       0.86      0.72      0.78       238
           1       0.76      0.88      0.81       238

    accuracy                           0.80       476
   macro avg       0.81      0.80      0.80       476
weighted avg       0.81      0.80      0.80       476



In [57]:
#Pruning technique(entropy) at depth 6= f1 score = 81% and accuracy = 80%

In [58]:
#Second Pruning technique: min_samples_leaf
'''for i in range(45,101):
    dt1=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)

    print("Min_samples leaf depth: ",i)
    print("Confusion matrix and classification report")
    dt1=create_model(dt1)'''

'for i in range(45,101):\n    dt1=DecisionTreeClassifier(random_state=1,min_samples_leaf=i)\n\n    print("Min_samples leaf depth: ",i)\n    print("Confusion matrix and classification report")\n    dt1=create_model(dt1)'

In [59]:
dt1=DecisionTreeClassifier(random_state=1,min_samples_leaf=47)

print("Confusion matrix and classification report")
dt1=create_model(dt1)

Confusion matrix and classification report
[[163  75]
 [ 34 204]]
              precision    recall  f1-score   support

           0       0.83      0.68      0.75       238
           1       0.73      0.86      0.79       238

    accuracy                           0.77       476
   macro avg       0.78      0.77      0.77       476
weighted avg       0.78      0.77      0.77       476



In [60]:
#Min samples leaf = recall = 86%, f1= 79% and accuracy 77%

In [61]:
#RandomForestTree(Bagging)
from sklearn.ensemble import RandomForestClassifier

In [62]:
'''for i in range(10,101):
    rfc=RandomForestClassifier(random_state=1,n_estimators=i)
    print("No. of Decision Trees: ",i)
    rfc=create_model(rfc)'''

'for i in range(10,101):\n    rfc=RandomForestClassifier(random_state=1,n_estimators=i)\n    print("No. of Decision Trees: ",i)\n    rfc=create_model(rfc)'

In [63]:
rfc=RandomForestClassifier(random_state=1,n_estimators=23)

rfc=create_model(rfc)
rfc.feature_importances_

[[214  24]
 [ 82 156]]
              precision    recall  f1-score   support

           0       0.72      0.90      0.80       238
           1       0.87      0.66      0.75       238

    accuracy                           0.78       476
   macro avg       0.79      0.78      0.77       476
weighted avg       0.79      0.78      0.77       476



array([0.05008077, 0.09451036, 0.13680087, 0.08947789, 0.13219011,
       0.01734925, 0.01040916, 0.01397095, 0.14674686, 0.12748022,
       0.06353732, 0.01442739, 0.10301885])

In [64]:
#recall score=66%(0.66), f1 score= 75%
#accuracy=(0.85)

In [65]:
from sklearn.ensemble import AdaBoostClassifier

In [66]:
for i in range(1,17):
    #create object
    ada=AdaBoostClassifier(random_state=1,n_estimators=i)
    print("No. of decision stumps: ",i)
    ada=create_model(ada)

No. of decision stumps:  1
[[125 113]
 [ 33 205]]
              precision    recall  f1-score   support

           0       0.79      0.53      0.63       238
           1       0.64      0.86      0.74       238

    accuracy                           0.69       476
   macro avg       0.72      0.69      0.68       476
weighted avg       0.72      0.69      0.68       476

No. of decision stumps:  2
[[125 113]
 [ 30 208]]
              precision    recall  f1-score   support

           0       0.81      0.53      0.64       238
           1       0.65      0.87      0.74       238

    accuracy                           0.70       476
   macro avg       0.73      0.70      0.69       476
weighted avg       0.73      0.70      0.69       476

No. of decision stumps:  3
[[138 100]
 [ 30 208]]
              precision    recall  f1-score   support

           0       0.82      0.58      0.68       238
           1       0.68      0.87      0.76       238

    accuracy                    

In [67]:
ada=AdaBoostClassifier(random_state=1,n_estimators=4)
ada=create_model(ada)
ada.feature_importances_

[[170  68]
 [ 41 197]]
              precision    recall  f1-score   support

           0       0.81      0.71      0.76       238
           1       0.74      0.83      0.78       238

    accuracy                           0.77       476
   macro avg       0.77      0.77      0.77       476
weighted avg       0.77      0.77      0.77       476



array([0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  , 0.25, 0.  , 0.25,
       0.  , 0.  ])

In [68]:
#ada boost (f1 score= 78% and accuracy= 77%)

In [69]:
#gradient Boosting Algo
from sklearn.ensemble import GradientBoostingClassifier

In [70]:
for i in range(10,101):
    gbc=GradientBoostingClassifier(random_state=1,n_estimators=i)
    print("No. of Decision Trees: ",i)
    gbc=create_model(gbc)

No. of Decision Trees:  10
[[166  72]
 [ 37 201]]
              precision    recall  f1-score   support

           0       0.82      0.70      0.75       238
           1       0.74      0.84      0.79       238

    accuracy                           0.77       476
   macro avg       0.78      0.77      0.77       476
weighted avg       0.78      0.77      0.77       476

No. of Decision Trees:  11
[[163  75]
 [ 34 204]]
              precision    recall  f1-score   support

           0       0.83      0.68      0.75       238
           1       0.73      0.86      0.79       238

    accuracy                           0.77       476
   macro avg       0.78      0.77      0.77       476
weighted avg       0.78      0.77      0.77       476

No. of Decision Trees:  12
[[163  75]
 [ 37 201]]
              precision    recall  f1-score   support

           0       0.81      0.68      0.74       238
           1       0.73      0.84      0.78       238

    accuracy                    

In [71]:
gbc=GradientBoostingClassifier(random_state=1,n_estimators=51)

gbc=create_model(gbc)

[[191  47]
 [ 48 190]]
              precision    recall  f1-score   support

           0       0.80      0.80      0.80       238
           1       0.80      0.80      0.80       238

    accuracy                           0.80       476
   macro avg       0.80      0.80      0.80       476
weighted avg       0.80      0.80      0.80       476



In [72]:
#gbc at 51:Recall : 0.80, f1 score = 80% and accuracy = 0.80

In [73]:
!pip install xgboost

In [74]:
from xgboost import XGBClassifier

In [75]:
for i in range(10,101):
    xgb=XGBClassifier(random_state=1,n_estimators=i,reg_alpha=1)
    print("No. of Decision Trees: ",i)
    xgb=create_model(xgb)

No. of Decision Trees:  10
[[195  43]
 [ 45 193]]
              precision    recall  f1-score   support

           0       0.81      0.82      0.82       238
           1       0.82      0.81      0.81       238

    accuracy                           0.82       476
   macro avg       0.82      0.82      0.82       476
weighted avg       0.82      0.82      0.82       476

No. of Decision Trees:  11
[[196  42]
 [ 50 188]]
              precision    recall  f1-score   support

           0       0.80      0.82      0.81       238
           1       0.82      0.79      0.80       238

    accuracy                           0.81       476
   macro avg       0.81      0.81      0.81       476
weighted avg       0.81      0.81      0.81       476

No. of Decision Trees:  12
[[200  38]
 [ 49 189]]
              precision    recall  f1-score   support

           0       0.80      0.84      0.82       238
           1       0.83      0.79      0.81       238

    accuracy                    

In [76]:
#12:F1 score : 0.81 and accuracy = 0.82

In [77]:
#SVM
from sklearn.svm import LinearSVC

In [78]:
#create object
svc=LinearSVC(random_state=1)

In [79]:
#call function
svc=create_model(svc)

[[172  66]
 [ 83 155]]
              precision    recall  f1-score   support

           0       0.67      0.72      0.70       238
           1       0.70      0.65      0.68       238

    accuracy                           0.69       476
   macro avg       0.69      0.69      0.69       476
weighted avg       0.69      0.69      0.69       476



In [80]:
#add error
svc1=LinearSVC(random_state=1,C=0.01)

In [81]:
svc1=create_model(svc1)

[[174  64]
 [ 79 159]]
              precision    recall  f1-score   support

           0       0.69      0.73      0.71       238
           1       0.71      0.67      0.69       238

    accuracy                           0.70       476
   macro avg       0.70      0.70      0.70       476
weighted avg       0.70      0.70      0.70       476



In [83]:
svc1=LinearSVC(random_state=1,C=0.08)
svc1=create_model(svc1)

[[172  66]
 [ 79 159]]
              precision    recall  f1-score   support

           0       0.69      0.72      0.70       238
           1       0.71      0.67      0.69       238

    accuracy                           0.70       476
   macro avg       0.70      0.70      0.70       476
weighted avg       0.70      0.70      0.70       476



In [84]:
svc1=LinearSVC(random_state=1,C=0.1)
svc1=create_model(svc1)

[[172  66]
 [ 83 155]]
              precision    recall  f1-score   support

           0       0.67      0.72      0.70       238
           1       0.70      0.65      0.68       238

    accuracy                           0.69       476
   macro avg       0.69      0.69      0.69       476
weighted avg       0.69      0.69      0.69       476



In [85]:
#non linear data
from sklearn.svm import SVC

In [86]:
#create object
p_svc=SVC(random_state=1,kernel='poly')

In [87]:
#call function
p_svc=create_model(p_svc)

[[193  45]
 [122 116]]
              precision    recall  f1-score   support

           0       0.61      0.81      0.70       238
           1       0.72      0.49      0.58       238

    accuracy                           0.65       476
   macro avg       0.67      0.65      0.64       476
weighted avg       0.67      0.65      0.64       476



In [88]:
r_svc=SVC(random_state=1,kernel='rbf')

In [89]:
r_svc=create_model(r_svc)

[[180  58]
 [ 69 169]]
              precision    recall  f1-score   support

           0       0.72      0.76      0.74       238
           1       0.74      0.71      0.73       238

    accuracy                           0.73       476
   macro avg       0.73      0.73      0.73       476
weighted avg       0.73      0.73      0.73       476



In [ ]:
#Logistic Regression
#recall=65% which is not good amd f1 score is 68% which is not good
#Decision tree classifier: recall score is 45% which is not good and difference is more than 20
#Pruning technique(Gini index) at depth 6= f1 score = 81% and accuracy = 80%
#Pruning technique(entropy) at depth 6= f1 score = 81% and accuracy = 80%
#Min samples leaf = recall = 86%, f1= 79% and accuracy 77%
#Random Forest #recall score=66%(0.66), f1 score= 75% accuracy=(0.85)
#ada boost (f1 score= 78% and accuracy= 77%)
#xgboost at 12:F1 score : 0.81 and accuracy = 0.82